define(['jquery','ModPage','modUtil'],
	function($, ModPage, modUtil) {
		
		var Home = ModPage.extend({
			
			// HEADER TABLE
			headerId: 'ID',
			headerNome: 'Nome',
			headerCpf: 'CPF',
			
			events:{
				'/loadSuccess': 'loadingTable',
				'/loadSuccess2': 'loadingTable2'
			},
						
			posRender: function(){
				
			},
			
			loadingTable: function(){
				this.publish('/loadingTable', 
						[{'item': this.headerId}, {'item': this.headerNome}, {'item': this.headerCpf}], 
						
						
						[{'linha':[{'item':'Teste1'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste2'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste3'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste4'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste5'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste6'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste7'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste8'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste9'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste10'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste11'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste12'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste13'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste14'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste15'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste16'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste17'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste18'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste19'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste20'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste21'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste22'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste23'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste24'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste25'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste26'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste27'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste28'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste29'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste30'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste31'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste32'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste33'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste34'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste35'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste36'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste37'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste38'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste39'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste40'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste41'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste42'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste43'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste44'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste45'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste46'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste47'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste48'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste49'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste50'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste51'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste52'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste53'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste54'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste55'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste56'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste57'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste58'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste59'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste60'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste61'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste62'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste63'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste64'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste65'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste66'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste67'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste68'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste69'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste70'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste71'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste72'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste73'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste74'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste75'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste76'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste77'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste78'}, {'item':'Teste'}, {'item':'Teste'}]},
						 {'linha':[{'item':'Teste79'}, {'item':'Teste'}, {'item':'Teste'}]}
						
					]);
			},
			
			loadingTable2: function(){
				this.publish('/loadingTable2', 
						[], 
						[{'linha':[{'item':'Home1'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home2'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home3'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home4'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home5'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home6'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home7'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home8'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home9'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home10'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home11'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home12'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home13'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home14'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home15'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home16'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home17'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home18'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home19'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home20'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home21'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home22'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home23'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home24'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home25'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home26'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home27'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home28'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home29'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home30'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home31'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home32'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home33'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home34'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home35'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home36'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home37'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home38'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home39'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home40'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home41'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home42'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home43'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home44'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home45'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home46'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home47'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home48'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home49'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home50'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home51'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home52'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home53'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home54'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home55'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home56'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home57'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home58'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home59'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home60'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home61'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home62'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home63'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home64'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home65'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home66'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home67'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home68'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home69'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home70'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home71'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home72'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home73'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home74'}, {'item':'Home'}, {'item':'Home'}]},
						 {'linha':[{'item':'Home75'}, {'item':'Home'}, {'item':'Home'}]}						
						
					]);
			}
		
		});
					
		return Home;
});